### ISSUE TITLE
Bug: Key/payload are not encoded in schema when schema is attached

### ISSUE THREAD

**Issue by lyuboxa** [ConduitIO/conduit-connector-postgres#216]
### Bug description

Schema is extracted and attached but the payload and key are not encoded.
The middle where in the SDK will do both extract then encode however the latter is missing in Postgres.

### Steps to reproduce

1. Create pipeline from postgres to file
2. Disable schema decoding on the file connector
3. Data comes out as plain text

```yaml
version: 2.0
pipelines:
  - id: pg-to-kaf
    status: running
    connectors:
      - id: pg.in
        type: source
        plugin: builtin:postgres
        settings:
          url: <pg-url>
          tables: test
      - id: file.out
        type: destination
        plugin: builtin:file
        settings:
          path: ./pg.out
          sdk.schema.extract.payload.enabled: false
          sdk.schema.extract.key.enabled: false
```

### Version

v0.9.1
